# Generated by Django 4.2.6 on 2023-11-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('pricePerNight', models.IntegerField()),
                ('primaryThumbnailImage', models.TextField()),
                ('secondaryImage', models.TextField()),
                ('description', models.TextField()),
                ('maximumGuests', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
